<a href="https://colab.research.google.com/github/sks95/python_basics/blob/main/numpy_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [13]:
# Create an array of 10 zeros

arr = np.zeros(10,dtype='int32')
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [16]:
# Create an array of 10 ones

arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
# Create an array of 10 fives

arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [21]:
# Create an array of integers from 10 to 50

arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [25]:
# Create an array of even integers from 10 to 50

arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [29]:
# Create a 3 x 4 matrix ranging from 0 to 12

arr = np.arange(12, dtype='int32').reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
# Create a 3 x 3 Identity matrix

arr = np.eye(3,3, dtype='int32')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)