<a href="https://colab.research.google.com/github/sks95/python_basics/blob/main/numpy_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create an array of 10 zeros

arr = np.zeros(10,dtype='int32')
(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [3]:
# Create an array of 10 ones

arr = np.ones(10)
(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Create an array of 10 fives

arr = np.ones(10)*5
(arr)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
# Create an array of integers from 10 to 50

arr = np.arange(10,51)
(arr)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
# Create an array of even integers from 10 to 50

arr = np.arange(10,51,2)
(arr)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
# Create a 3 x 4 matrix ranging from 0 to 12

arr = np.arange(12, dtype='int32').reshape(3,4)
(arr)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [8]:
# Create a 3 x 3 Identity matrix

arr = np.eye(3,3, dtype='int32')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [9]:
# Use Numpy to generate a random number between 0 and 1

num = np.random.normal(0,1,1)
num

array([0.60796668])

In [10]:
# Use Numpy to generate an array of 25 Random numbers sampled from a normal distribution

arr = np.random.normal(0,1,25)
arr

array([-0.30752735,  0.19345367,  1.1271233 ,  0.38880061,  0.78016542,
       -0.46355325, -1.07096515,  1.96510265, -0.56104124,  0.22451957,
        2.795523  ,  0.62215697,  0.28372061, -0.01131788,  0.35163923,
        0.8500266 ,  0.85396856,  0.61055255, -0.32286501,  0.34990066,
       -0.27822194, -0.91492333, -0.12791205, -2.21551481,  1.26843356])

In [11]:
# Create an (10x10)array having number from 0.01 to 1 increasing by 0.01

arr = np.linspace(0.01,1, num=100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Numpy Indexing & Slicing

In [12]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

extract array

[ [12,13,14],

[17,18,19],

[22,23,24] ]

In [13]:
new_ar = ar[2:,1:4]
new_ar

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

extract array

[ [14, 13, 12],

[19, 18, 17],

[24, 23, 22] ]

In [14]:
new_ar1 = new_ar[:,::-1]

extract array

[ [24, 23, 22],

[19, 18, 17],

[14, 13, 12],
]

In [15]:
new_ar2 = new_ar1[::-1,:];
new_ar2

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

# Split Concatenate

In [16]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

Split array to generate 3 arrays with content

[2,3,4]

[5, 6]

[]

[7,8,9]

In [17]:
np.split(ar, [3,5])


[array([2, 3, 4]), array([5, 6]), array([7, 8, 9])]

# 2D

In [18]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

Concatinate array to create new array with content

[ [1,2,3],

[4,5,6],

[7,8,9] ]

In [19]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

Concatinate array to create new array with content

[

[1,2,3, 7,8,9, 10],

[4,5,6, 11, 12, 13, 14]

]

In [21]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

# Broadcasting and Indexing

count how many numbers are minimum in ar

example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [22]:
arr = np.round(np.random.rand(10)*10)
print(arr)
print(arr.min())
unique,counts = np.unique(arr, return_counts=True)
dict(zip(unique,counts))

[8. 8. 5. 1. 2. 8. 8. 8. 0. 5.]
0.0


{0.0: 1, 1.0: 1, 2.0: 1, 5.0: 2, 8.0: 5}

In [23]:
ar = np.round(np.random.rand(10)*10)
ar

array([10.,  1.,  9., 10.,  6.,  2., 10.,  6.,  4.,  4.])

create new array containing all numbers which are smaller than 10 in ar

In [24]:
ar_new = ar[ar<10]
ar_new

array([1., 9., 6., 2., 6., 4., 4.])

create new array containing all numbers which are in range [3, 11] in ar

In [25]:
ar_new = ar[(ar>3) & (ar<11)]
ar_new

array([10.,  9., 10.,  6., 10.,  6.,  4.,  4.])

Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5

In [26]:
arr = np.ones(15, dtype='int32')*2
arr1 = np.ones(5, dtype='int32')*-5

res = np.concatenate([arr,arr1])
print(res)
len(res)

[ 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2 -5 -5 -5 -5 -5]


20

Sum Min Max of All Elements

In [27]:
mat = np.array(
    [[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]]
)
mat

array([[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]])

In [28]:
print(mat.min())
print(mat.max())
print(mat.sum())

1.0
99.0
2124.0


Standard Deviation of Matrix

In [29]:
print(mat.std())

30.531452634946806


Sum of all columns of matrix

In [30]:
print(mat.sum(axis=0))

[347. 151. 254. 245. 232. 196. 237. 188. 214.  60.]


create array of dimension same as arr using arr.shape variable

In [34]:
arr = np.arange(100).reshape(4,5,5)
print(arr)
dim = arr.shape

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [36]:
arr2 = np.arange(arr.size).reshape(arr.shape)
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])