<a href="https://colab.research.google.com/github/sks95/python_basics/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Tutorials
# Numpy is an array processing package

import numpy as np;

my_1st = [1,2,3,4,5];
arr = np.array(my_1st);
print(arr);
print(type(arr));
arr.shape
arr

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 3]
 [4 5 6]
 [7 9 8]
 [7 6 5]]
[[1 2 3 4 5]
 [3 4 5 6 7]
 [9 8 7 6 5]]


In [ ]:
# Multinested array
my_list1 = [1,2,3,4,5];
my_list2 = [3,4,5,6,7];
my_list3 = [9,8,7,6,5];

arr = np.array([my_list1,my_list2,my_list3]);
print(arr)
print(arr.shape)
print(arr.reshape(5,3));
print(arr)

# Indexing in array

print(arr[0:1,:]);
print(arr[0:2,0:2]);
print(arr[1:3,3:5]);
print(arr[1:,1:]);

[[1 2 3 4 5]
 [3 4 5 6 7]
 [9 8 7 6 5]]
(3, 5)
[[1 2 3]
 [4 5 3]
 [4 5 6]
 [7 9 8]
 [7 6 5]]
[[1 2 3 4 5]
 [3 4 5 6 7]
 [9 8 7 6 5]]
[[1 2 3 4 5]]
[[1 2]
 [3 4]]
[[6 7]
 [6 5]]
[[4 5 6 7]
 [8 7 6 5]]


In [ ]:
# define range 

test=np.arange(0,20,step=2);
print(test);
test[5:]=100;
print(test);
print(np.linspace(1,10,50));

[ 0  2  4  6  8 10 12 14 16 18]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[  0   2   4   6   8 100 100 100 100 100]


In [ ]:
# concept of shallow copy and deep copy
x = np.array([1,2,3]);
y = x;  
z = np.copy(x);   
x[0] = 10
print(x);
print(y);
print(z);

a = np.array([1, 'm', [2,3,4]],dtype=object);
print(a);
b = np.copy(a);
b[2][0] = 10;
print(a);

# To ensure all elements within an object array are copied, use copy.deepcopy
import copy;
c = np.array([1, 'm', [2,3,4]], dtype=object);
d = copy.deepcopy(c);
print("c =",c);
d[2][0] = 10;
print("d =",d);
print("c =",c);

[10  2  3]
[10  2  3]
[1 2 3]
[1 'm' list([2, 3, 4])]
[1 'm' list([10, 3, 4])]
c = [1 'm' list([2, 3, 4])]
d = [1 'm' list([10, 3, 4])]
c = [1 'm' list([2, 3, 4])]


In [ ]:
# Some conditions useful for Exploratory Data Analysis
print(test);
print(test>=100)
print(test*2)
print(test[test<100])

[  0   2   4   6   8 100 100 100 100 100]
[False False False False False  True  True  True  True  True]
[  0   4   8  12  16 200 200 200 200 200]
[0 2 4 6 8]


In [ ]:
# Create arrays and Reshape

print(np.arange(0,10).reshape(5,2))
print(np.ones(6))     # by default float -> tabhi . aya
print(np.ones((2,5),dtype=int))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1. 1. 1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# create random distribution

print(np.random.rand(3,3))
print(np.random.randn(4,4))  # n -> standard normal distribution
print(np.random.randint(40,100,8)) # randint(low_val, high_val, no_of_val)

[[0.8451214  0.54732289 0.3210615 ]
 [0.10660234 0.39243668 0.7405664 ]
 [0.49479865 0.5335026  0.79067442]]
[[-0.58586168  0.44185663 -0.54967591  0.22750074]
 [ 1.14709367 -0.8899114   0.16927388 -0.0674095 ]
 [ 0.89487577 -1.0814201   0.2369916   1.04370922]
 [ 0.60408361 -1.46332744 -1.44686453  2.05692393]]


array([72, 68, 66, 63, 77, 93, 91, 89])