<a href="https://colab.research.google.com/github/sks95/python_basics/blob/main/numpy_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

In [40]:
# Create an array of 10 zeros

arr = np.zeros(10,dtype='int32')
(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [41]:
# Create an array of 10 ones

arr = np.ones(10)
(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Create an array of 10 fives

arr = np.ones(10)*5
(arr)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [43]:
# Create an array of integers from 10 to 50

arr = np.arange(10,51)
(arr)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
# Create an array of even integers from 10 to 50

arr = np.arange(10,51,2)
(arr)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [45]:
# Create a 3 x 4 matrix ranging from 0 to 12

arr = np.arange(12, dtype='int32').reshape(3,4)
(arr)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [46]:
# Create a 3 x 3 Identity matrix

arr = np.eye(3,3, dtype='int32')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [47]:
# Use Numpy to generate a random number between 0 and 1

num = np.random.normal(0,1,1)
num

array([0.34439942])

In [48]:
# Use Numpy to generate an array of 25 Random numbers sampled from a normal distribution

arr = np.random.normal(0,1,25)
arr

array([ 0.10497552,  1.17495289, -1.99258708, -0.39105623, -1.34811158,
        1.50420338,  1.01456247, -1.93977459,  0.09283607, -0.01044613,
       -0.19810262, -0.48410209,  0.61773105,  0.77762379, -0.30428914,
       -0.72450561, -0.41015467, -0.74103626, -0.64175384,  1.49688296,
        0.40969862,  1.60031602,  0.20529   ,  0.01574028, -0.18043514])

In [49]:
# Create an (10x10)array having number from 0.01 to 1 increasing by 0.01

arr = np.linspace(0.01,1, num=100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Numpy Indexing & Slicing

In [50]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

extract array

[ [12,13,14],

[17,18,19],

[22,23,24] ]

In [51]:
new_ar = ar[2:,1:4]
new_ar

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

extract array

[ [14, 13, 12],

[19, 18, 17],

[24, 23, 22] ]

In [52]:
new_ar1 = new_ar[:,::-1]

extract array

[ [24, 23, 22],

[19, 18, 17],

[14, 13, 12],
]

In [53]:
new_ar2 = new_ar1[::-1,:];
new_ar2

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

# Split Concatenate

In [54]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

Split array to generate 3 arrays with content

[2,3,4]

[5, 6]

[]

[7,8,9]

In [55]:
np.split(ar, [3,5])


[array([2, 3, 4]), array([5, 6]), array([7, 8, 9])]

# 2D

In [56]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

Concatinate array to create new array with content

[ [1,2,3],

[4,5,6],

[7,8,9] ]

In [57]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

Concatinate array to create new array with content

[

[1,2,3, 7,8,9, 10],

[4,5,6, 11, 12, 13, 14]

]

In [59]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

# Broadcasting and Indexing

count how many numbers are minimum in ar

example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [60]:
arr = np.round(np.random.rand(10)*10)
arr

array([3., 8., 5., 6., 5., 8., 1., 3., 3., 9.])

create new array containing all numbers which are smaller than 10 in ar

In [61]:
ar = np.round(np.random.rand(10)*10)
ar

array([ 3., 10.,  5.,  1.,  1., 10.,  7.,  5.,  7.,  4.])

create new array containing all numbers which are in range [3, 11] in ar

In [62]:
ar = np.arange(3,12)