<a href="https://colab.research.google.com/github/sks95/python_basics/blob/main/Numpy_pepcoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
type(arr)

# number of dimension
arr.ndim

1

In [7]:
arr.size

5

In [9]:
# numpy array is homogeneous

arr.dtype

dtype('int64')

In [12]:
arr = np.array([1,2,3,4,5], dtype='uint8')
arr.dtype

dtype('uint8')

In [15]:
arr = np.array([1,2,3,4,5.5])
arr.dtype

dtype('float64')

Time execution

In [20]:
l1 = [1]*1000

arr = np.ones(1000,dtype='uint8')

In [22]:
%timeit sum(l1)

100000 loops, best of 5: 6.67 µs per loop


In [24]:
%timeit arr.sum()

The slowest run took 162.20 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3 µs per loop


In [26]:
# List keeps a new copy

l = [1,2,3,4]
l2 = l[1:3]
print(l)
print(l2)
l2[0] = 1000
print(l)
print(l2)

[1, 2, 3, 4]
[2, 3]
[1, 2, 3, 4]
[1000, 3]


In [27]:
# Numpy array keeps same copy and changes made in old version

arr = np.array([1,2,3,4])
arr2 = arr[1:3]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[   1 1000    3    4]
[1000    3]


In [28]:
# Using .copy() to create separate copy

arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[1000    3]


In [30]:
arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]
])

In [32]:
arr.ndim

2

In [42]:
arr.shape

(4, 3)

In [41]:
arr[::-1,::-1]

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [44]:
arr[1:3,2:]

array([[6],
       [9]])

In [48]:
arr = np.arange(2,9,2)
print(arr)

[2 4 6 8]


In [50]:
np.random.permutation(arr)

array([2, 4, 6, 8])

In [51]:
np.random.randint(1,5)

2

In [53]:
np.random.rand(4,2)

array([[0.2070706 , 0.8353296 ],
       [0.3159185 , 0.63825684],
       [0.35182217, 0.87117575],
       [0.37238061, 0.99073961]])